### PR TITLE
update Stable to Next

### PR DESCRIPTION
**Pull request by fgiudici**
tentative update

### CODE REVIEW

**Comment by kkaempf** [comment]
Umm, 96 files 🤯 

Can you briefly elaborate _what_ you did for this PR ?

**Comment by fgiudici** [comment]
> Umm, 96 files exploding_head
> 
> Can you briefly elaborate _what_ you did for this PR ?

mainly:
 `cp -a docs/* versioned_docs/version-stable/`
 
 Then, I adapted only one file: `versioned_sidebars/version-stable-sidebars.json` from `sidebars.js`

**Comment by juadk** [comment]
> Umm, 96 files exploding_head
> 
> Can you briefly elaborate _what_ you did for this PR ?

I think lot of changes comes from screenshots I added to the UI quickstart :smile:

**Comment by fgiudici** [comment]
rebased on main, kept following changes as fixups (we'll merge as a squashed commit).
Just done another `cp -a docs/* versioned_docs/version-stable/`, and added missing part to the versioned sidebar.

**Review by davidcassany — APPROVED** [review]
LGTM :+1:

**Pull request merged**
