### PR TITLE
quickstart: correct registration name in iso prep explanation

### PR DESCRIPTION
**Pull request by tserong**
Signed-off-by: Tim Serong <tserong@suse.com>

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
Thanks!

**Comment by kkaempf** [comment]
Why is merging still blocked ? 🤔

**Comment by tserong** [comment]
I think it wants me to gpg sign my commit. Hang on...

**Comment by tserong** [comment]
...there we go :-)

**Pull request merged**
