### PR TITLE
[Phase 1] Elemental docs migration

### PR DESCRIPTION
**Pull request by nunix**
- Created new Docusaurus site
- Copied the Elemental docs from rancher/elemental
- Applied same configuration as rancher/elemental

Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>

### CODE REVIEW

**Review by kkaempf — APPROVED** [review]
lgtm

**Comment by Itxaka** [comment]
do we store the deps in yarn.lock or package-lock.json?? There is two different lock files but AFAIK we use the yarn.lock for the dependencies no? Im asking becuase the dependency review is failing due some package in the package-lock.json.....should we drop that file? Should we check both?

**Comment by nunix** [comment]
> do we store the deps in yarn.lock or package-lock.json?? There is two different lock files but AFAIK we use the yarn.lock for the dependencies no? Im asking becuase the dependency review is failing due some package in the package-lock.json.....should we drop that file? Should we check both?

sorry missed this one.
Going further, if possible, it would be only `yarn.lock`. I'll update the repo's README to indicate that yarn should be used.

**Review by Itxaka — APPROVED** [review]

**Review by davidcassany — APPROVED** [review]
Nice :+1:

**Review by kkaempf — APPROVED** [review]
let's merge as-is and do the actual review once the new doc site is up

**Pull request merged**
