### PR TITLE
Rpi images moved to new URL

### PR DESCRIPTION
**Pull request by frelon**
From https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging:/containers/rpi.raw
To   https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Stable/containers/rpi.raw

### CODE REVIEW

**Comment by kkaempf** [comment]
Imho, we shouldn't advertise `Staging` but point people to `Stable` instead.

**Review by kkaempf — APPROVED** [review]
:+1:

**Comment by kkaempf** [comment]
It should be noted that aarch64 images will stay on opensuse.org for the time being (and not be promoted to suse.com) until we fully support ARM as an architecture.

**Review by davidcassany — CHANGES_REQUESTED** [review]
I am not following this change. Stable project is no longer updated as stable releases published under `suse.com` from staging. As far as I understand there are NO stable RPi builds and our best effort is keeping Staging in good shape as much as possible.

URL should have been:
https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging/containers/rpi.raw

Looks like the actual error was a small typo (note extra `:` after `Staging` in current docs) 😓

**Review by davidcassany — APPROVED** [review]
Looks to me, we just updated Stable OBS project to only include the RPi image which builds from the container abailable in `registry.suse.com`

**Pull request merged**
