### PR TITLE
Docusaurus update to 2.4.0

### PR DESCRIPTION
**Pull request by nunix**
Update of Docusaurus to the latest stable release: 2.4.0

This PR addresses several open PRs by dependabot:
#63 webpack update to 5.77.0
#66 plugin-google-gtag update to 2.4.0
#67 preset-classic update to 2.4.0
#68 module-type-aliases update to 2.4.0

Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>

### CODE REVIEW

**Comment by kkaempf** [comment]
What about #55 ?!

**Review by fgiudici — APPROVED** [review]
🎉

**Review by frelon — APPROVED** [review]
Very nice! :rocket:

**Comment by nunix** [comment]
> What about #55 ?!

@kkaempf I wanted to be able to close it too, however it's still in development on Docusaurus side and it's a breaking change. So unfortunately we need to still wait for this one.

**Pull request merged**
