### PR TITLE
elemental-with-rancher-vmware

### PR DESCRIPTION
**Pull request by bashlion**

### CODE REVIEW

**Comment by kkaempf** [comment]
This documentation is probably too exhaustive, as it explains how to install the Elemental UI extension for example.

I'd merge it as-is and split it later into multiple parts, like installing the UI extension.


@bashlion as this is a substantial contribution (thank you for that 🙏🏻 !) we would need you to signoff your commit.

**Comment by bashlion** [comment]
> 

Thank you.. I have signed off :)

**Review by kkaempf — APPROVED** [review]
Thanks for this outstanding contribution !

**Review by fgiudici — APPROVED** [review]
Pretty nice

**Review by nunix — APPROVED** [review]

**Pull request merged**
